### ISSUE TITLE
Adding code-lens commands to run bazel commands

### ISSUE THREAD

**Issue by romannikov** [zaucy/zed-starlark#6]
Bazel has runnable rules, like:
```
go_binary(
    name = "main",
    embed = [":main_lib"],
    visibility = ["//visibility:public"],
)
```
and buildable, like:
```
go_library(
    name = "main_lib",
    srcs = ["main.go"],
    deps = [
    ],
    visibility = ["//visibility:private"],
)
```
Currently the extension doesn't have code lens commands to run/build these rules. Is it possible to add them?

**Comment by zaucy** [comment]
I believe the LSP needs to support codelens. The main LSP used in this repo is [starpls](https://github.com/withered-magic/starpls) which I believe doesn't have codelens support.
